name: Build and Deploy CDDA Web

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 0 * * *" # Daily build
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4

            - name: Setup emsdk
              uses: mymindstorm/setup-emsdk@v14

            - name: Install Dependencies
              run: |
                  sudo apt update
                  sudo apt install -y git cmake python3-pip pkg-config zlib1g-dev libfreetype6-dev

            - name: Clone CDDA source
              run: |
                  git clone --depth 1 https://github.com/CleverRaven/Cataclysm-DDA.git cdda
                  cd cdda
                  git submodule update --init --recursive

            - name: Build CDDA for Web
              run: |
                  cd cdda
                  make -j`nproc` NATIVE=emscripten BACKTRACE=0 TILES=1 TESTS=0 RUNTESTS=0 RELEASE=1 LINTJSON=0 \
                    WARNINGS=" \
                        -Wno-error -Wall -Wextra \
                        -Wformat-signedness \
                        -Wlogical-op \
                        -Wmissing-declarations \
                        -Wmissing-noreturn \
                        -Wpedantic \
                        -Wunused-macros" \
                    cataclysm-tiles.js

            - name: Copy output to temp directory
              run: |
                  ls -lh .
                  mkdir -p output
                  cp cdda/cataclysm-tiles.js output/
                  cp cdda/cataclysm-tiles.wasm output/
                  cp cdda/cataclysm-tiles.data output/

            - name: Publish to data branch
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./output
                  publish_branch: data
                  force_orphan: true
